Nicolas sastoque
globant-scalable-platforms/bootcamp-java-spring-may-2019 pull request #21
Opened 2019-06-03 05:36 UTC by NicolasZon

2019-06-03 15:35 UTC, estigma88 requested changes
Excellent job, only a little comment there

2019-06-03 15:35 UTC, estigma88 commented on Week1/NicolasSastoque/functional/src/main/java/StreamsModel/List.java
> +        ArrayList<Element> southAmericaElement = new ArrayList<>(
This is redundant, Arrays.asList gives you the list already created

2019-06-06 04:30 UTC, chejunior commented on Week1/NicolasSastoque/unit-test/src/test/java/kata/business/AccountServiceImplTest.java
> +    @Test
Is better to use here something like this:

@Test(expected=AccountException.class)

so later you need to remove the try-catch clause, and also the asserts ones, this should be enough to pass in an easier way the fail test 👍

2019-06-06 04:32 UTC, chejunior requested changes

2019-06-06 04:32 UTC, chejunior commented on Week1/NicolasSastoque/unit-test/src/test/java/kata/business/AccountServiceImplTest.java
> +    @Test
Is better to use here something like this:

@test(expected=AccountException.class)

so later you need to remove the try-catch clause, and also the asserts ones, this should be enough to pass in an easier way the fail test 👍

2019-06-20 21:36 UTC, merged